klapse.h: Try to use "int" instead of "short" to fix build errors.
The build errors like:
error: redeclaration of 'kcal_red' with a different type: 'unsigned short' vs 'unsigned int'

After I look through the source,the most of the variable used "int".

Only for test...